# datasource config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sms?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: jingjinduo
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
