# datasource config

spring:
  profiles:
    active: jjd
# mybatis config
mybatis-plus:
  mapper-locations: classpath:mappers/*.xml
  type-aliases-package: com.huhi.sms.model
  global-config:
    db-config:
      id-type: auto
server:
  #端口号
  port: 8380